{
    "name": "Hotkey demand group",
    "version": "17.0.1.0.1",
    "category": "Accounting/Accounting",
    "license": "LGPL-3",
    "author": "Pavlo Zub",
    "maintainer": "Hotkey",
    "website": "hotkey.ua",
    "depends": [
        "base",
        "account",
        "sale",
        "stock",
        "purchase",
        "warehouse_stock_request_app",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/demand_group_views.xml",
        "views/purchase_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_request_views.xml",
        "views/stock_move_views.xml",
        "views/sale_views.xml",
        "views/stock_lot_views.xml",
    ],
    "installable": True,
    "auto_install": False,
}
